"""Export the batch-mode 24h day as the hackathon-required sample data.

Writes deliverables/sample_data/{security_telemetry.jsonl, transactions.jsonl}
plus labels.json (ground-truth scenario tags). Run: `make export-sample-data`.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

from sutra.config import SEED  # noqa: E402
from sutra.generator.replay import batch_events  # noqa: E402
from sutra.generator.world import build_world  # noqa: E402
from sutra.schemas import Txn, wire_dict  # noqa: E402

OUT = ROOT / "deliverables" / "sample_data"


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    world = build_world(SEED)
    events = batch_events(world, SEED)

    sec = OUT / "security_telemetry.jsonl"
    txn = OUT / "transactions.jsonl"
    labels: dict[str, str] = {}
    n_sec = n_txn = 0
    with sec.open("w") as fs, txn.open("w") as ft:
        for ev in events:
            row = wire_dict(ev, keep_label=True)
            labels[ev.event_id] = ev.scenario
            line = json.dumps(row) + "\n"
            if isinstance(ev, Txn):
                ft.write(line)
                n_txn += 1
            else:
                fs.write(line)
                n_sec += 1

    counts: dict[str, int] = {}
    for lab in labels.values():
        key = lab.split("-")[0] if lab.startswith("noise") else lab
        counts[key] = counts.get(key, 0) + 1

    (OUT / "labels.json").write_text(json.dumps({
        "seed": SEED,
        "description": "Ground-truth scenario tag per event_id. 'benign' = background "
                       "noise, 'noise' = borderline single-signal lookalike, A/B/C = "
                       "the three attack scenarios.",
        "counts": counts,
        "labels": labels,
    }, indent=2))

    (OUT / "README.md").write_text(
        f"""# SUTRA sample data (seed {SEED})

Synthetic 24h of a mid-size bank's telemetry, generated by
`backend/sutra/generator/`. No real PII — all IDs are obviously synthetic.

- `security_telemetry.jsonl` — {n_sec:,} events: auth_login, edr_alert, tls_session,
  payee_added, password_reset (one JSON object per line).
- `transactions.jsonl` — {n_txn:,} core-banking transactions.
- `labels.json` — generator ground truth: which events belong to attack scenarios
  A (account takeover + structuring), B (compromised terminal), C (HNDL exfil) vs
  benign noise vs borderline single-signal lookalikes.

This is the sample data referenced in the demo video. Regenerate with
`make export-sample-data`.
""")
    print(f"wrote {n_sec:,} security + {n_txn:,} txn events → {OUT}")
    print("label counts:", counts)


if __name__ == "__main__":
    main()
